#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload
nitrogen --restore &
xrandr --dpi 100x100
# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4    # Use alt as the main modifier

#herbstclient load ${TAG_NAMES[0]} '(clients max:0)'

# tags (en)
tag_names=( {1..6} )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# custom commands
hc keybind $Mod-Return spawn terminator
hc keybind $Mod-Shift-v spawn qutebrowser
hc keybind $Mod-v spawn waterfox
hc keybind $Mod-Shift-p spawn pavucontrol
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-s split horizontal 0.5
hc keybind Print spawn scrot -e 'mv $f /home/fives/Wallpapers/desktop'

# gaps
hc keybind $Mod-Shift-g spawn /home/fives/.config/majicks/gaps 
hc keybind $Mod-g spawn /home/fives/.config/majicks/ungaps

# herbstluftwm layout manager
hc keybind Control-section spawn ~/bin/hlwm_lm.sh load
hc keybind Control-apostrophe spawn ~/bin/hlwm_lm.sh save

# focusing clients
hc keybind $Mod-left    focus left
hc keybind $Mod-down    focus down
hc keybind $Mod-up      focus up
hc keybind $Mod-right   focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-period       split   bottom  0.5
hc keybind $Mod-comma       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-e split explode

# resizing frames
resizestep=0.03
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# cycle through tags
hc keybind $Mod-adiaeresis use_index +1 --skip-visible
hc keybind $Mod-odiaeresis use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-Tab cycle_layout 1
hc keybind $Mod-Shift-space floating toggle
hc keybind $Mod-Shift-m fullscreen toggle

# mouse
#hc mouseunbind --all
hc mousebind $Mod-B1 move
hc mousebind $Mod-B2 zoom
hc mousebind $Mod-B3 resize

# focus
hc keybind Control-period   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-u jumpto urgent

# colors
hc set frame_border_active_color '#683248'
hc set frame_border_normal_color '#0F0A1A'
hc set frame_bg_active_color '#0F0A1A'
hc set frame_bg_normal_color '#0F0A1A'
hc set window_border_active_color '#8F2B34'
hc set window_border_normal_color '#0F0A1A'
hc set window_border_urgent_color '#0F0A1A'
hc set frame_border_width 0
hc set window_border_width 0
hc set window_border_inner_width 0
hc set always_show_frame 0
hc set frame_gap 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0

# add overlapping window borders
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule title="Open Image" pseudotile=on
hc rule title="Save As" pseudotile=on
hc rule title="Save file" pseudotile=on

hc rule class=Dwb tag=term focus=on
hc rule class=mpv tag=term focus=on
hc rule class=wine tag=term focus=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1280x1024+0+0 1920x1080+1280+0
# or simply:
hc detect_monitors

## panel for main monitor -- ignore second monitor
#hc pad 0 14 0 0 0
hc keybind $Mod-d spawn rofi -font "Yanc YancFont Regular 8" -show drun -width 482 -location 0 -lines 16 -bw 2 -hide-scrollbar 
hc keybind $Mod-Shift-n spawn nemo
hc keybind $Mod-n spawn polo

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" &
done
